declare type Field = {
    id: string,
    companyId: string,
    companyName: string,
    databaseId: string,
    databaseName: string,
    tableId: string,
    tableName: string,
    code: string,
    name: string,
    type: string,
    length: string | number,
    primaryKey: string | number,
    unique: string | number,
    identity: string | number,
    index: string | number,
    splitField: string | number,
    versionField: string | number,
    add: string | number,
    addWidth: string | number,
    addSort: string | number,
    edit: string | number,
    editWidth: string | number,
    editSort: string | number,
    detail: string | number,
    detailWidth: string | number,
    detailSort: string | number,
    table: string | number,
    tableWidth: string | number,
    tableSort: string | number,
    list: string | number,
    listWidth: string | number,
    listSort: string | number,
    print: string | number,
    printWidth: string | number,
    printSort: string | number,
    export: string | number,
    exportWidth: string | number,
    exportSort: string | number,
    import: string | number,
    importWidth: string | number,
    importSort: string | number,
    abbreviation: string,
    description: string,
    color: string,
    sort: string | number
    creator: string,
    createTime: string,
    updater: string,
    updateTime: string,
    version: string,
    status: string | number,
};