declare type Operation = {
    id: string,
    companyId: string,
    companyName: string,
    code: string,
    name: string,
    abbreviation: string,
    description: string,
    color: string,
    sort: string | number,
    creator: string,
    createTime: string,
    updater: string,
    updateTime: string,
    version: string,
    status: string | number,
};