declare type Resource = {
    id: string,
    companyId: string,
    companyName: string,
    type: string,
    code: string,
    name: string,
    server: string,
    port: number | string,
    user: string,
    password: string,
    charSet: string,
    abbreviation: string,
    description: string,
    color: string,
    sort: number | string,
    creator: string,
    createTime: string,
    updater: string,
    updateTime: string,
    version: string,
    status: number | string,

};