declare type Table = {
    id: string,
    companyId: string,
    companyName: string,
    databaseId: string,
    databaseName: string,
    code: string,
    name: string,
    splitType: string,
    abbreviation: string,
    description: string,
    color: string,
    sort: number | number,
    creator: string,
    createTime: string,
    updater: string,
    updateTime: string,
    version: string,
    status: number | number,
};